#Name- Yash Bhargava
#Rollno- 2115500160 (53)
#Section- T

In [ ]:
import pandas as pd #Importing pandas module with pd as alias name

**read_csv()** method in pandas is used to load a csv file into pandas dataFrame

---


**to_string()** method is used to print all the complete rows without skipping 
middle rows.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/data_panda.csv")
print(df.head(169).to_string())

     Duration   Pulse  Maxpulse  Calories        DOB
0        60.0   110.0     130.0     409.1   5/5/1975
1        60.0   117.0     145.0     479.0   5/5/1975
2        60.0   103.0     135.0     340.0        NaN
3        45.0   109.0     175.0     282.4   5/7/1975
4        45.0   117.0     148.0     406.0   9/8/1989
5        60.0   102.0     127.0     300.0   9/9/1989
6        60.0   110.0     136.0     374.0   5/5/1975
7        45.0   104.0     134.0     253.3   5/6/1975
8        30.0   109.0       NaN     195.1   5/7/1975
9        60.0    98.0     124.0     269.0   1/7/1988
10       60.0   103.0     147.0     329.3   1/8/1988
11       60.0   100.0     120.0     250.7   1/9/1988
12       60.0   106.0     128.0     345.3   7/4/1988
13       60.0   104.0     132.0     379.3   7/5/1988
14       60.0    98.0     123.0     275.0   7/6/1988
15       60.0  1000.0     120.0     215.2   7/7/1988
16       60.0   100.0     120.0     300.0   7/8/1988
17       45.0    90.0     112.0       NaN   7/9/1988
18       60.0   103.0     123.0     323.0   4/4/1986
19       45.0    97.0       NaN     243.0   4/6/1979
20       60.0   108.0     131.0     364.2   4/7/1979
21       45.0   100.0     119.0     282.0   4/8/1979
22       60.0   130.0     101.0     300.0   9/1/1989
23       45.0   105.0     132.0     246.0   9/2/1989
24       60.0   102.0     126.0     334.5   9/3/1989
25       60.0   100.0     120.0     250.0   9/4/1989
26       60.0    92.0     118.0     241.0   4/4/1987
27       60.0   103.0     132.0       NaN   4/5/1987
28       60.0   100.0     132.0     280.0   4/6/1987
29       60.0   102.0     129.0     380.3   4/7/1987
30       60.0    92.0     115.0     243.0   4/8/1987
31       45.0    90.0     112.0     180.1   4/9/1987
32       60.0   101.0     124.0     299.0   6/1/1964
33       60.0    93.0     113.0     223.0   3/2/1980
34       60.0   107.0     136.0     361.0   3/3/1980
35       60.0   114.0     140.0     415.0   3/4/1980
36       60.0   102.0     127.0     300.0   8/9/1983
37       60.0   100.0     120.0     300.0   4/5/1987
38       60.0   100.0     120.0     300.0   2/2/1983
39       45.0   104.0     129.0     266.0   6/6/1986
40       45.0    90.0     112.0     180.1   6/7/1986
41       60.0    98.0     126.0     286.0   1/2/1951
42       60.0   100.0     122.0     329.4   2/9/1972
43      160.0   111.0     138.0     400.0   1/2/1951
44       60.0   111.0     131.0     397.0   1/3/1951
45       60.0    99.0     119.0     273.0   1/4/1951
46       60.0   109.0     153.0     387.6   1/5/1951
47       45.0   111.0     136.0     300.0   1/6/1951
48       45.0   108.0     129.0     298.0   9/5/1985
49       60.0   111.0     139.0     397.6   9/4/1989
50       60.0   107.0     136.0     380.2   4/4/1987
51       80.0   123.0     146.0     643.1   4/5/1987
52       60.0   106.0     130.0     263.0   4/6/1987
53       60.0   118.0     151.0     486.0   4/7/1987
54       30.0   136.0     175.0     238.0   4/8/1987
55       60.0   121.0     146.0     450.7   4/9/1987
56       60.0   118.0     121.0     413.0   6/1/1964
57       45.0   115.0     144.0     305.0   3/2/1980
58       20.0   153.0     172.0     226.4   3/3/1980
59       45.0   123.0     152.0     321.0   3/4/1980
60      210.0   108.0     160.0    1376.0   8/9/1983
61      160.0   110.0     137.0    1034.4   4/5/1987
62      160.0   109.0     135.0     853.0   2/2/1983
63       45.0   118.0     141.0     341.0   6/6/1986
64       20.0   110.0     130.0     131.4   6/7/1986
65      180.0    90.0     130.0     800.4   1/2/1951
66      150.0   105.0     135.0     873.4   2/9/1972
67      150.0   107.0     130.0     816.0   1/2/1951
68       20.0   106.0     136.0     110.4   1/3/1951
69      300.0   108.0     143.0    1500.2   1/4/1951
70      150.0    97.0     129.0    1115.0   1/5/1951
71       60.0   109.0     153.0     387.6   1/6/1951
72       90.0   100.0     127.0     700.0   9/5/1985
73      150.0    97.0     127.0     953.2   1/4/1951
74       45.0   114.0     146.0     304.0   1/5/1951
75       90.0    98.0     125.0     563.2   1/6/1951
76       45.0   105.0     134.0     251.0   9/5/1985
77       45.0   110.0     141.0     300.0   9/4/1989
78      120.0   100.0     130.0     500.4   4/4/1987
79      270.0   100.0     131.0    1729.0   4/5/1987
80       30.0   159.0     182.0     319.2   4/6/1987
81       45.0   149.0     169.0     344.0   4/7/1987
82       30.0   103.0     139.0     151.1   4/8/1987
83      120.0   100.0     130.0     500.0   4/9/1987
84       45.0   100.0     120.0     225.3   6/1/1964
85       30.0   151.0     170.0     300.0   3/2/1980
86       45.0   102.0     136.0     234.0   3/3/1980
87      120.0   100.0     157.0    1000.1   3/4/1980
88       45.0   129.0     103.0     242.0   8/9/1983
89       20.0    83.0     107.0      50.3   1/4/1951
90      180.0   101.0     127.0     600.1   1/5/1951
91       45.0   107.0     137.0       NaN   1/6/1951
92      -20.0    90.0     107.0     105.3   9/5/1985
93       15.0    80.0     100.0      50.5   9/4/1989
94       20.0   150.0     171.0     127.4   4/4/1987
95       20.0   151.0     168.0     229.4   4/5/1987
96       30.0    95.0     128.0     128.2   4/6/1987
97       25.0   152.0     168.0     244.2   4/7/1987
98       30.0   109.0     131.0     188.2   4/8/1987
99       90.0    93.0     124.0     604.1   4/9/1987
100      20.0    95.0     112.0      77.7   6/1/1964
101      90.0    90.0     110.0     500.0   3/2/1980
102      90.0    90.0     100.0     500.0   3/3/1980
103      90.0    90.0     100.0     500.4   3/4/1980
104      30.0    92.0     108.0      92.7   8/9/1983
105      30.0    93.0     128.0     124.0   8/9/1974
106     180.0    90.0     120.0     800.3   5/8/1980
107      30.0    90.0     120.0      86.2   8/9/1983
108      90.0    90.0     120.0     500.3   1/4/1951
109     210.0   137.0     184.0    1860.4   1/5/1951
110      60.0   102.0     124.0     325.2   1/6/1951
111      45.0   107.0     124.0     275.0   9/5/1985
112      15.0   124.0     139.0     124.2   9/4/1989
113      45.0   100.0     120.0     225.3   4/4/1987
114      60.0   108.0     131.0     367.6   4/5/1987
115      60.0   108.0     151.0     351.7   4/6/1987
116      60.0   116.0     141.0     443.0   4/7/1987
117      60.0    97.0     122.0     277.4   4/8/1987
118      60.0   105.0     125.0       NaN   4/9/1987
119      60.0   103.0     124.0     332.7   6/1/1964
120      30.0   112.0     137.0     193.9   3/2/1980
121      45.0   100.0     120.0     100.7   3/3/1980
122      60.0   119.0     169.0     336.7   3/4/1980
123      60.0   107.0     127.0     344.9   8/9/1983
124      60.0   111.0     151.0     368.5   8/9/1983
125      60.0    98.0     122.0     271.0   1/4/1951
126      60.0    97.0     124.0     275.3   1/5/1951
127      60.0   109.0     127.0     382.0   1/6/1951
128      90.0    99.0     125.0     466.4   9/5/1985
129      60.0   114.0     151.0     384.0   9/4/1989
130      60.0   104.0     134.0     342.5   4/4/1987
131      60.0   107.0     138.0     357.5   4/5/1987
132      60.0   103.0     133.0     335.0   4/6/1987
133      60.0   106.0     132.0     327.5   4/7/1987
134      60.0   103.0     136.0     339.0   4/8/1987
135      20.0   136.0     156.0     189.0   4/9/1987
136      45.0   117.0     143.0     317.7   6/1/1964
137      45.0   115.0     137.0     318.0   3/2/1980
138      45.0   113.0     138.0     308.0   3/3/1980
139      20.0   141.0     162.0     222.4   3/4/1980
140      60.0   108.0     135.0     390.0   8/9/1983
141      60.0    97.0     127.0       NaN   8/9/1983
142      45.0   100.0     120.0     250.4   1/4/1951
143      45.0   122.0     149.0     335.4   1/5/1951
144      60.0   136.0     170.0     470.2   1/6/1951
145      45.0   106.0     126.0     270.8   9/5/1985
146      60.0   107.0     136.0     400.0   9/4/1989
147      60.0   112.0     146.0     361.9   4/4/1987
148      30.0   103.0     127.0     185.0   4/5/1987
149      60.0   110.0     150.0     409.4   4/6/1987
150      60.0   106.0     134.0     343.0   4/7/1987
151      60.0   109.0     129.0     353.2   4/8/1987
152      60.0   109.0     138.0     374.0   4/9/1987
153      30.0   150.0     167.0     275.8   6/1/1964
154      60.0   105.0     128.0     328.0  7/27/2781
155      60.0   111.0     151.0     368.5   3/3/1980
156      60.0    97.0     131.0     270.4   3/4/1980
157      60.0   100.0     120.0     270.4   8/9/1983
158      60.0   114.0     150.0     382.8   8/9/1983
159      30.0    80.0     120.0     240.9   1/4/1951
160      30.0    85.0     120.0     250.4   1/5/1951
161      45.0    90.0     130.0     260.4   1/6/1951
162      45.0    95.0     130.0     270.0   9/5/1985
163      45.0   100.0     140.0     280.9   9/4/1989
164      60.0   105.0     140.0     290.8   4/4/1987
165      60.0   110.0     145.0     300.0   4/5/1987
166      60.0   115.0     145.0     310.2   4/6/1987
167      75.0   120.0     150.0     320.4   4/7/1987
168      75.0   125.0     150.0     330.4   4/8/1987

dataFrame head() method takes x, as it' s parameter, where x are the number of rows to be taken from beginning.

---
By default it takes out 5 rows from the dataset if not parameter is taken.


---
Syntax:- df.head(x)

In [ ]:
df1 = df.head(169)
print(df1)

     Duration  Pulse  Maxpulse  Calories       DOB
0        60.0  110.0     130.0     409.1  5/5/1975
1        60.0  117.0     145.0     479.0  5/5/1975
2        60.0  103.0     135.0     340.0       NaN
3        45.0  109.0     175.0     282.4  5/7/1975
4        45.0  117.0     148.0     406.0  9/8/1989
..        ...    ...       ...       ...       ...
164      60.0  105.0     140.0     290.8  4/4/1987
165      60.0  110.0     145.0     300.0  4/5/1987
166      60.0  115.0     145.0     310.2  4/6/1987
167      75.0  120.0     150.0     320.4  4/7/1987
168      75.0  125.0     150.0     330.4  4/8/1987

[169 rows x 5 columns]

dataFrame tail() method takes x, as it' s parameter, where x is the number of rows to be taken from the end of dataset.

---
By default it takes out 5 rows from the dataset if not parameter is taken.


---
Syntax:- df.tail(x)

In [ ]:
df2 = df1.tail()
print(df2)

     Duration  Pulse  Maxpulse  Calories       DOB
164      60.0  105.0     140.0     290.8  4/4/1987
165      60.0  110.0     145.0     300.0  4/5/1987
166      60.0  115.0     145.0     310.2  4/6/1987
167      75.0  120.0     150.0     320.4  4/7/1987
168      75.0  125.0     150.0     330.4  4/8/1987

dropna() method of dataFrame removes the rows that contain NaN values.

---


syntax:- df.dropna()

---


it has a optional attribute inplac = True, if set to True then makes changes to original dataFrame otherwise returns a new dataFrame.

In [ ]:
df3 = df1.dropna()
print(df3)

     Duration  Pulse  Maxpulse  Calories       DOB
0        60.0  110.0     130.0     409.1  5/5/1975
1        60.0  117.0     145.0     479.0  5/5/1975
3        45.0  109.0     175.0     282.4  5/7/1975
4        45.0  117.0     148.0     406.0  9/8/1989
5        60.0  102.0     127.0     300.0  9/9/1989
..        ...    ...       ...       ...       ...
164      60.0  105.0     140.0     290.8  4/4/1987
165      60.0  110.0     145.0     300.0  4/5/1987
166      60.0  115.0     145.0     310.2  4/6/1987
167      75.0  120.0     150.0     320.4  4/7/1987
168      75.0  125.0     150.0     330.4  4/8/1987

[161 rows x 5 columns]

fillna() method of dataFrame replaces the non numeric values with some desired values.

In [ ]:
df4 = df.fillna(130)
print(df4)

     Duration  Pulse  Maxpulse  Calories       DOB
0        60.0  110.0     130.0     409.1  5/5/1975
1        60.0  117.0     145.0     479.0  5/5/1975
2        60.0  103.0     135.0     340.0       130
3        45.0  109.0     175.0     282.4  5/7/1975
4        45.0  117.0     148.0     406.0  9/8/1989
..        ...    ...       ...       ...       ...
306     130.0  130.0     130.0     130.0       130
307     130.0  130.0     130.0     130.0       130
308     130.0  130.0     130.0     130.0       130
309     130.0  130.0     130.0     130.0       130
310     130.0  130.0     130.0     130.0       130

[311 rows x 5 columns]

Replacing the non numeric values of 'Calories' column with mean of the column.

In [ ]:
df5 = df
df5['Calories'].fillna(df['Calories'].mean(), inplace = True)

In [ ]:
print(df5)

     Duration  Pulse  Maxpulse    Calories       DOB
0        60.0  110.0     130.0  409.100000  5/5/1975
1        60.0  117.0     145.0  479.000000  5/5/1975
2        60.0  103.0     135.0  340.000000       NaN
3        45.0  109.0     175.0  282.400000  5/7/1975
4        45.0  117.0     148.0  406.000000  9/8/1989
..        ...    ...       ...         ...       ...
306       NaN    NaN       NaN  375.790244       NaN
307       NaN    NaN       NaN  375.790244       NaN
308       NaN    NaN       NaN  375.790244       NaN
309       NaN    NaN       NaN  375.790244       NaN
310       NaN    NaN       NaN  375.790244       NaN

[311 rows x 5 columns]

In [ ]:
print(df5)

     Duration  Pulse  Maxpulse    Calories       DOB
0        60.0  110.0     130.0  409.100000  5/5/1975
1        60.0  117.0     145.0  479.000000  5/5/1975
2        60.0  103.0     135.0  340.000000       NaN
3        45.0  109.0     175.0  282.400000  5/7/1975
4        45.0  117.0     148.0  406.000000  9/8/1989
..        ...    ...       ...         ...       ...
306       NaN    NaN       NaN  375.790244       NaN
307       NaN    NaN       NaN  375.790244       NaN
308       NaN    NaN       NaN  375.790244       NaN
309       NaN    NaN       NaN  375.790244       NaN
310       NaN    NaN       NaN  375.790244       NaN

[311 rows x 5 columns]

Replacing the non numeric values of 'Calories' column with median of the column.

In [ ]:
df6 = df5
df6['Calories'].fillna(df['Calories'].median(), inplace = True)
print(df6)

     Duration  Pulse  Maxpulse    Calories       DOB
0        60.0  110.0     130.0  409.100000  5/5/1975
1        60.0  117.0     145.0  479.000000  5/5/1975
2        60.0  103.0     135.0  340.000000       NaN
3        45.0  109.0     175.0  282.400000  5/7/1975
4        45.0  117.0     148.0  406.000000  9/8/1989
..        ...    ...       ...         ...       ...
306       NaN    NaN       NaN  375.790244       NaN
307       NaN    NaN       NaN  375.790244       NaN
308       NaN    NaN       NaN  375.790244       NaN
309       NaN    NaN       NaN  375.790244       NaN
310       NaN    NaN       NaN  375.790244       NaN

[311 rows x 5 columns]

Replacing the non numeric values of 'Calories' column with mode of the column.

In [ ]:
df7 = df5
df7['Calories'].fillna(df['Calories'].mode()[0], inplace = True)
print(df7)

     Duration  Pulse  Maxpulse    Calories       DOB
0        60.0  110.0     130.0  409.100000  5/5/1975
1        60.0  117.0     145.0  479.000000  5/5/1975
2        60.0  103.0     135.0  340.000000       NaN
3        45.0  109.0     175.0  282.400000  5/7/1975
4        45.0  117.0     148.0  406.000000  9/8/1989
..        ...    ...       ...         ...       ...
306       NaN    NaN       NaN  375.790244       NaN
307       NaN    NaN       NaN  375.790244       NaN
308       NaN    NaN       NaN  375.790244       NaN
309       NaN    NaN       NaN  375.790244       NaN
310       NaN    NaN       NaN  375.790244       NaN

[311 rows x 5 columns]

iloc[] is used to fetch the columns on the based of indexes from complete dataFrame.

In [ ]:
df8 = df7
print(df8.iloc[[2,5,7]])

   Duration  Pulse  Maxpulse  Calories       DOB
2      60.0  103.0     135.0     340.0       NaN
5      60.0  102.0     127.0     300.0  9/9/1989
7      45.0  104.0     134.0     253.3  5/6/1975

loc[] is used to fetch columns from complete dataFrame on the basis of column headings.

In [ ]:
print((df.loc[:168, 'Duration':'Maxpulse']).to_string())

     Duration   Pulse  Maxpulse
0        60.0   110.0     130.0
1        60.0   117.0     145.0
2        60.0   103.0     135.0
3        45.0   109.0     175.0
4        45.0   117.0     148.0
5        60.0   102.0     127.0
6        60.0   110.0     136.0
7        45.0   104.0     134.0
8        30.0   109.0       NaN
9        60.0    98.0     124.0
10       60.0   103.0     147.0
11       60.0   100.0     120.0
12       60.0   106.0     128.0
13       60.0   104.0     132.0
14       60.0    98.0     123.0
15       60.0  1000.0     120.0
16       60.0   100.0     120.0
17       45.0    90.0     112.0
18       60.0   103.0     123.0
19       45.0    97.0       NaN
20       60.0   108.0     131.0
21       45.0   100.0     119.0
22       60.0   130.0     101.0
23       45.0   105.0     132.0
24       60.0   102.0     126.0
25       60.0   100.0     120.0
26       60.0    92.0     118.0
27       60.0   103.0     132.0
28       60.0   100.0     132.0
29       60.0   102.0     129.0
30       60.0    92.0     115.0
31       45.0    90.0     112.0
32       60.0   101.0     124.0
33       60.0    93.0     113.0
34       60.0   107.0     136.0
35       60.0   114.0     140.0
36       60.0   102.0     127.0
37       60.0   100.0     120.0
38       60.0   100.0     120.0
39       45.0   104.0     129.0
40       45.0    90.0     112.0
41       60.0    98.0     126.0
42       60.0   100.0     122.0
43      160.0   111.0     138.0
44       60.0   111.0     131.0
45       60.0    99.0     119.0
46       60.0   109.0     153.0
47       45.0   111.0     136.0
48       45.0   108.0     129.0
49       60.0   111.0     139.0
50       60.0   107.0     136.0
51       80.0   123.0     146.0
52       60.0   106.0     130.0
53       60.0   118.0     151.0
54       30.0   136.0     175.0
55       60.0   121.0     146.0
56       60.0   118.0     121.0
57       45.0   115.0     144.0
58       20.0   153.0     172.0
59       45.0   123.0     152.0
60      210.0   108.0     160.0
61      160.0   110.0     137.0
62      160.0   109.0     135.0
63       45.0   118.0     141.0
64       20.0   110.0     130.0
65      180.0    90.0     130.0
66      150.0   105.0     135.0
67      150.0   107.0     130.0
68       20.0   106.0     136.0
69      300.0   108.0     143.0
70      150.0    97.0     129.0
71       60.0   109.0     153.0
72       90.0   100.0     127.0
73      150.0    97.0     127.0
74       45.0   114.0     146.0
75       90.0    98.0     125.0
76       45.0   105.0     134.0
77       45.0   110.0     141.0
78      120.0   100.0     130.0
79      270.0   100.0     131.0
80       30.0   159.0     182.0
81       45.0   149.0     169.0
82       30.0   103.0     139.0
83      120.0   100.0     130.0
84       45.0   100.0     120.0
85       30.0   151.0     170.0
86       45.0   102.0     136.0
87      120.0   100.0     157.0
88       45.0   129.0     103.0
89       20.0    83.0     107.0
90      180.0   101.0     127.0
91       45.0   107.0     137.0
92      -20.0    90.0     107.0
93       15.0    80.0     100.0
94       20.0   150.0     171.0
95       20.0   151.0     168.0
96       30.0    95.0     128.0
97       25.0   152.0     168.0
98       30.0   109.0     131.0
99       90.0    93.0     124.0
100      20.0    95.0     112.0
101      90.0    90.0     110.0
102      90.0    90.0     100.0
103      90.0    90.0     100.0
104      30.0    92.0     108.0
105      30.0    93.0     128.0
106     180.0    90.0     120.0
107      30.0    90.0     120.0
108      90.0    90.0     120.0
109     210.0   137.0     184.0
110      60.0   102.0     124.0
111      45.0   107.0     124.0
112      15.0   124.0     139.0
113      45.0   100.0     120.0
114      60.0   108.0     131.0
115      60.0   108.0     151.0
116      60.0   116.0     141.0
117      60.0    97.0     122.0
118      60.0   105.0     125.0
119      60.0   103.0     124.0
120      30.0   112.0     137.0
121      45.0   100.0     120.0
122      60.0   119.0     169.0
123      60.0   107.0     127.0
124      60.0   111.0     151.0
125      60.0    98.0     122.0
126      60.0    97.0     124.0
127      60.0   109.0     127.0
128      90.0    99.0     125.0
129      60.0   114.0     151.0
130      60.0   104.0     134.0
131      60.0   107.0     138.0
132      60.0   103.0     133.0
133      60.0   106.0     132.0
134      60.0   103.0     136.0
135      20.0   136.0     156.0
136      45.0   117.0     143.0
137      45.0   115.0     137.0
138      45.0   113.0     138.0
139      20.0   141.0     162.0
140      60.0   108.0     135.0
141      60.0    97.0     127.0
142      45.0   100.0     120.0
143      45.0   122.0     149.0
144      60.0   136.0     170.0
145      45.0   106.0     126.0
146      60.0   107.0     136.0
147      60.0   112.0     146.0
148      30.0   103.0     127.0
149      60.0   110.0     150.0
150      60.0   106.0     134.0
151      60.0   109.0     129.0
152      60.0   109.0     138.0
153      30.0   150.0     167.0
154      60.0   105.0     128.0
155      60.0   111.0     151.0
156      60.0    97.0     131.0
157      60.0   100.0     120.0
158      60.0   114.0     150.0
159      30.0    80.0     120.0
160      30.0    85.0     120.0
161      45.0    90.0     130.0
162      45.0    95.0     130.0
163      45.0   100.0     140.0
164      60.0   105.0     140.0
165      60.0   110.0     145.0
166      60.0   115.0     145.0
167      75.0   120.0     150.0
168      75.0   125.0     150.0

The index property returns the index information of the DataFrame.

In [ ]:
for x in df8.index:
  if df8.loc[x,"Duration"] > 60:
    df8.loc[x,"Duration"] = 80
print(df8)

     Duration  Pulse  Maxpulse    Calories       DOB
0        60.0  110.0     130.0  409.100000  5/5/1975
1        60.0  117.0     145.0  479.000000  5/5/1975
2        60.0  103.0     135.0  340.000000       NaN
3        45.0  109.0     175.0  282.400000  5/7/1975
4        45.0  117.0     148.0  406.000000  9/8/1989
..        ...    ...       ...         ...       ...
306       NaN    NaN       NaN  375.790244       NaN
307       NaN    NaN       NaN  375.790244       NaN
308       NaN    NaN       NaN  375.790244       NaN
309       NaN    NaN       NaN  375.790244       NaN
310       NaN    NaN       NaN  375.790244       NaN

[311 rows x 5 columns]

Pandas drop_duplicates() method helps in removing duplicates from the Pandas Dataframe In Python.

In [ ]:
print(df8.drop_duplicates(inplace = True))
print(df8.to_string())

None
     Duration   Pulse  Maxpulse     Calories        DOB
0        60.0   110.0     130.0   409.100000   5/5/1975
1        60.0   117.0     145.0   479.000000   5/5/1975
2        60.0   103.0     135.0   340.000000        NaN
3        45.0   109.0     175.0   282.400000   5/7/1975
4        45.0   117.0     148.0   406.000000   9/8/1989
5        60.0   102.0     127.0   300.000000   9/9/1989
6        60.0   110.0     136.0   374.000000   5/5/1975
7        45.0   104.0     134.0   253.300000   5/6/1975
8        30.0   109.0       NaN   195.100000   5/7/1975
9        60.0    98.0     124.0   269.000000   1/7/1988
10       60.0   103.0     147.0   329.300000   1/8/1988
11       60.0   100.0     120.0   250.700000   1/9/1988
12       60.0   106.0     128.0   345.300000   7/4/1988
13       60.0   104.0     132.0   379.300000   7/5/1988
14       60.0    98.0     123.0   275.000000   7/6/1988
15       60.0  1000.0     120.0   215.200000   7/7/1988
16       60.0   100.0     120.0   300.000000   7/8/1988
17       45.0    90.0     112.0   375.790244   7/9/1988
18       60.0   103.0     123.0   323.000000   4/4/1986
19       45.0    97.0       NaN   243.000000   4/6/1979
20       60.0   108.0     131.0   364.200000   4/7/1979
21       45.0   100.0     119.0   282.000000   4/8/1979
22       60.0   130.0     101.0   300.000000   9/1/1989
23       45.0   105.0     132.0   246.000000   9/2/1989
24       60.0   102.0     126.0   334.500000   9/3/1989
25       60.0   100.0     120.0   250.000000   9/4/1989
26       60.0    92.0     118.0   241.000000   4/4/1987
27       60.0   103.0     132.0   375.790244   4/5/1987
28       60.0   100.0     132.0   280.000000   4/6/1987
29       60.0   102.0     129.0   380.300000   4/7/1987
30       60.0    92.0     115.0   243.000000   4/8/1987
31       45.0    90.0     112.0   180.100000   4/9/1987
32       60.0   101.0     124.0   299.000000   6/1/1964
33       60.0    93.0     113.0   223.000000   3/2/1980
34       60.0   107.0     136.0   361.000000   3/3/1980
35       60.0   114.0     140.0   415.000000   3/4/1980
36       60.0   102.0     127.0   300.000000   8/9/1983
37       60.0   100.0     120.0   300.000000   4/5/1987
38       60.0   100.0     120.0   300.000000   2/2/1983
39       45.0   104.0     129.0   266.000000   6/6/1986
40       45.0    90.0     112.0   180.100000   6/7/1986
41       60.0    98.0     126.0   286.000000   1/2/1951
42       60.0   100.0     122.0   329.400000   2/9/1972
43       80.0   111.0     138.0   400.000000   1/2/1951
44       60.0   111.0     131.0   397.000000   1/3/1951
45       60.0    99.0     119.0   273.000000   1/4/1951
46       60.0   109.0     153.0   387.600000   1/5/1951
47       45.0   111.0     136.0   300.000000   1/6/1951
48       45.0   108.0     129.0   298.000000   9/5/1985
49       60.0   111.0     139.0   397.600000   9/4/1989
50       60.0   107.0     136.0   380.200000   4/4/1987
51       80.0   123.0     146.0   643.100000   4/5/1987
52       60.0   106.0     130.0   263.000000   4/6/1987
53       60.0   118.0     151.0   486.000000   4/7/1987
54       30.0   136.0     175.0   238.000000   4/8/1987
55       60.0   121.0     146.0   450.700000   4/9/1987
56       60.0   118.0     121.0   413.000000   6/1/1964
57       45.0   115.0     144.0   305.000000   3/2/1980
58       20.0   153.0     172.0   226.400000   3/3/1980
59       45.0   123.0     152.0   321.000000   3/4/1980
60       80.0   108.0     160.0  1376.000000   8/9/1983
61       80.0   110.0     137.0  1034.400000   4/5/1987
62       80.0   109.0     135.0   853.000000   2/2/1983
63       45.0   118.0     141.0   341.000000   6/6/1986
64       20.0   110.0     130.0   131.400000   6/7/1986
65       80.0    90.0     130.0   800.400000   1/2/1951
66       80.0   105.0     135.0   873.400000   2/9/1972
67       80.0   107.0     130.0   816.000000   1/2/1951
68       20.0   106.0     136.0   110.400000   1/3/1951
69       80.0   108.0     143.0  1500.200000   1/4/1951
70       80.0    97.0     129.0  1115.000000   1/5/1951
71       60.0   109.0     153.0   387.600000   1/6/1951
72       80.0   100.0     127.0   700.000000   9/5/1985
73       80.0    97.0     127.0   953.200000   1/4/1951
74       45.0   114.0     146.0   304.000000   1/5/1951
75       80.0    98.0     125.0   563.200000   1/6/1951
76       45.0   105.0     134.0   251.000000   9/5/1985
77       45.0   110.0     141.0   300.000000   9/4/1989
78       80.0   100.0     130.0   500.400000   4/4/1987
79       80.0   100.0     131.0  1729.000000   4/5/1987
80       30.0   159.0     182.0   319.200000   4/6/1987
81       45.0   149.0     169.0   344.000000   4/7/1987
82       30.0   103.0     139.0   151.100000   4/8/1987
83       80.0   100.0     130.0   500.000000   4/9/1987
84       45.0   100.0     120.0   225.300000   6/1/1964
85       30.0   151.0     170.0   300.000000   3/2/1980
86       45.0   102.0     136.0   234.000000   3/3/1980
87       80.0   100.0     157.0  1000.100000   3/4/1980
88       45.0   129.0     103.0   242.000000   8/9/1983
89       20.0    83.0     107.0    50.300000   1/4/1951
90       80.0   101.0     127.0   600.100000   1/5/1951
91       45.0   107.0     137.0   375.790244   1/6/1951
92      -20.0    90.0     107.0   105.300000   9/5/1985
93       15.0    80.0     100.0    50.500000   9/4/1989
94       20.0   150.0     171.0   127.400000   4/4/1987
95       20.0   151.0     168.0   229.400000   4/5/1987
96       30.0    95.0     128.0   128.200000   4/6/1987
97       25.0   152.0     168.0   244.200000   4/7/1987
98       30.0   109.0     131.0   188.200000   4/8/1987
99       80.0    93.0     124.0   604.100000   4/9/1987
100      20.0    95.0     112.0    77.700000   6/1/1964
101      80.0    90.0     110.0   500.000000   3/2/1980
102      80.0    90.0     100.0   500.000000   3/3/1980
103      80.0    90.0     100.0   500.400000   3/4/1980
104      30.0    92.0     108.0    92.700000   8/9/1983
105      30.0    93.0     128.0   124.000000   8/9/1974
106      80.0    90.0     120.0   800.300000   5/8/1980
107      30.0    90.0     120.0    86.200000   8/9/1983
108      80.0    90.0     120.0   500.300000   1/4/1951
109      80.0   137.0     184.0  1860.400000   1/5/1951
110      60.0   102.0     124.0   325.200000   1/6/1951
111      45.0   107.0     124.0   275.000000   9/5/1985
112      15.0   124.0     139.0   124.200000   9/4/1989
113      45.0   100.0     120.0   225.300000   4/4/1987
114      60.0   108.0     131.0   367.600000   4/5/1987
115      60.0   108.0     151.0   351.700000   4/6/1987
116      60.0   116.0     141.0   443.000000   4/7/1987
117      60.0    97.0     122.0   277.400000   4/8/1987
118      60.0   105.0     125.0   375.790244   4/9/1987
119      60.0   103.0     124.0   332.700000   6/1/1964
120      30.0   112.0     137.0   193.900000   3/2/1980
121      45.0   100.0     120.0   100.700000   3/3/1980
122      60.0   119.0     169.0   336.700000   3/4/1980
123      60.0   107.0     127.0   344.900000   8/9/1983
124      60.0   111.0     151.0   368.500000   8/9/1983
125      60.0    98.0     122.0   271.000000   1/4/1951
126      60.0    97.0     124.0   275.300000   1/5/1951
127      60.0   109.0     127.0   382.000000   1/6/1951
128      80.0    99.0     125.0   466.400000   9/5/1985
129      60.0   114.0     151.0   384.000000   9/4/1989
130      60.0   104.0     134.0   342.500000   4/4/1987
131      60.0   107.0     138.0   357.500000   4/5/1987
132      60.0   103.0     133.0   335.000000   4/6/1987
133      60.0   106.0     132.0   327.500000   4/7/1987
134      60.0   103.0     136.0   339.000000   4/8/1987
135      20.0   136.0     156.0   189.000000   4/9/1987
136      45.0   117.0     143.0   317.700000   6/1/1964
137      45.0   115.0     137.0   318.000000   3/2/1980
138      45.0   113.0     138.0   308.000000   3/3/1980
139      20.0   141.0     162.0   222.400000   3/4/1980
140      60.0   108.0     135.0   390.000000   8/9/1983
141      60.0    97.0     127.0   375.790244   8/9/1983
142      45.0   100.0     120.0   250.400000   1/4/1951
143      45.0   122.0     149.0   335.400000   1/5/1951
144      60.0   136.0     170.0   470.200000   1/6/1951
145      45.0   106.0     126.0   270.800000   9/5/1985
146      60.0   107.0     136.0   400.000000   9/4/1989
147      60.0   112.0     146.0   361.900000   4/4/1987
148      30.0   103.0     127.0   185.000000   4/5/1987
149      60.0   110.0     150.0   409.400000   4/6/1987
150      60.0   106.0     134.0   343.000000   4/7/1987
151      60.0   109.0     129.0   353.200000   4/8/1987
152      60.0   109.0     138.0   374.000000   4/9/1987
153      30.0   150.0     167.0   275.800000   6/1/1964
154      60.0   105.0     128.0   328.000000  7/27/2781
155      60.0   111.0     151.0   368.500000   3/3/1980
156      60.0    97.0     131.0   270.400000   3/4/1980
157      60.0   100.0     120.0   270.400000   8/9/1983
158      60.0   114.0     150.0   382.800000   8/9/1983
159      30.0    80.0     120.0   240.900000   1/4/1951
160      30.0    85.0     120.0   250.400000   1/5/1951
161      45.0    90.0     130.0   260.400000   1/6/1951
162      45.0    95.0     130.0   270.000000   9/5/1985
163      45.0   100.0     140.0   280.900000   9/4/1989
164      60.0   105.0     140.0   290.800000   4/4/1987
165      60.0   110.0     145.0   300.000000   4/5/1987
166      60.0   115.0     145.0   310.200000   4/6/1987
167      80.0   120.0     150.0   320.400000   4/7/1987
168      80.0   125.0     150.0   330.400000   4/8/1987
169       NaN     NaN       NaN   375.790244        NaN